# Generated by Django 2.1.2 on 2018-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20181006_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/user.png', upload_to='pic_folder'),
        ),
    ]
